package icloud

import (
	"fmt"
	"time"

	"github.com/teambition/rrule-go"
)

// maxOccurrencesPerSeries bounds the number of occurrences expanded for a
// single recurring series, as protection against a pathological RRULE (e.g.
// FREQ=MINUTELY without UNTIL/COUNT over a 366-day range).
const maxOccurrencesPerSeries = 2000

// ExpandOccurrences expands a recurring event within [rangeStart, rangeEnd].
// Handles RRULE + EXDATE (exclusions); RECURRENCE-ID overrides replace the
// matching generated occurrence (compared at second precision, in UTC);
// overrides falling inside the range but absent from the generated series
// (moved out of their original slot) are still included.
// maxOccurrences bounds the expansion; if <= 0, the package default is used.
func ExpandOccurrences(master Event, overrides []Event, rangeStart, rangeEnd time.Time, maxOccurrences int) ([]Event, error) {
	if maxOccurrences <= 0 {
		maxOccurrences = maxOccurrencesPerSeries
	}

	if master.Recurrence == "" {
		if eventOverlaps(master, rangeStart, rangeEnd) {
			return []Event{master}, nil
		}
		return nil, nil
	}

	ropt, err := rrule.StrToROption(master.Recurrence)
	if err != nil {
		return nil, fmt.Errorf("invalid RRULE (uid=%s): %w", master.UID, err)
	}
	// Do NOT force .UTC() here: RFC 5545 requires the recurrence to follow
	// the local WALL CLOCK time of the Dtstart (TZID), not a fixed UTC
	// instant. Converting to UTC would destroy the Location and pin every
	// occurrence to the original Dtstart's UTC offset, shifting it by 1h
	// from the expected wall clock time as soon as a DST change happens in
	// between. If the event is already in Z (UTC), StartTime.Location() is
	// already time.UTC and no information is lost.
	ropt.Dtstart = master.StartTime

	rule, err := rrule.NewRRule(*ropt)
	if err != nil {
		return nil, fmt.Errorf("invalid RRULE (uid=%s): %w", master.UID, err)
	}

	set := &rrule.Set{}
	set.RRule(rule)
	for _, ex := range master.exDates {
		set.ExDate(ex.UTC())
	}

	// duration MUST be computed before calling Between: it is used to widen
	// the lower bound (see below) so occurrences starting before rangeStart
	// but spilling into the range are not lost.
	duration := master.EndTime.Sub(master.StartTime)

	// Lower bound widened by `duration`: an occurrence starting before
	// rangeStart can still overlap the range if it spills into it (e.g. an
	// overnight 22:00 to 02:00 slot). set.Between filters by START time;
	// without this widening, those occurrences would be lost even though the
	// non-recurring path (eventOverlaps) would include them. The upper bound
	// stays inc=true on the rrule-go side (it deliberately over-selects);
	// the eventOverlaps filter below brings the semantics back to the
	// half-open [rangeStart, rangeEnd) used everywhere else.
	lowerBound := rangeStart.Add(-duration)
	occTimes := set.Between(lowerBound.UTC(), rangeEnd.UTC(), true)
	if len(occTimes) > maxOccurrences {
		occTimes = occTimes[:maxOccurrences]
	}

	overrideByRecID := make(map[int64]Event, len(overrides))
	for _, o := range overrides {
		overrideByRecID[o.recurrenceID.UTC().Unix()] = o
	}
	used := make(map[int64]bool, len(overrideByRecID))

	out := make([]Event, 0, len(occTimes))
	for _, occ := range occTimes {
		// Keep only occurrences that genuinely overlap
		// [rangeStart, rangeEnd) once rebuilt with their full duration; the
		// widened lower bound above deliberately over-selects, and this
		// filter restores the exact eventOverlaps semantics (consistent
		// with the non-recurring path).
		if !eventOverlaps(Event{StartTime: occ, EndTime: occ.Add(duration)}, rangeStart, rangeEnd) {
			continue
		}
		key := occ.UTC().Unix()
		if ov, ok := overrideByRecID[key]; ok {
			out = append(out, ov)
			used[key] = true
			continue
		}
		clone := master
		clone.StartTime = occ
		clone.EndTime = occ.Add(duration)
		clone.exDates = nil
		out = append(out, clone)
	}

	// Overrides falling inside the range but absent from the series
	// generated by rrule-go (e.g. moved out of their original slot).
	for key, ov := range overrideByRecID {
		if used[key] {
			continue
		}
		if eventOverlaps(ov, rangeStart, rangeEnd) {
			out = append(out, ov)
		}
	}

	if len(out) > maxOccurrences {
		out = out[:maxOccurrences]
	}

	return out, nil
}

// eventOverlaps tests the half-open [start,end) overlap of an event with
// [rangeStart, rangeEnd].
func eventOverlaps(e Event, rangeStart, rangeEnd time.Time) bool {
	return e.StartTime.Before(rangeEnd) && e.EndTime.After(rangeStart)
}
